export interface NakshatraDetailItem {
  index: number;
  nameEng: string;
  nameHin: string;
  nameGuj: string;
  symbolEng: string;
  symbolHin: string;
  symbolGuj: string;
  deityEng: string;
  deityHin: string;
  deityGuj: string;
  lordEng: string;
  lordHin: string;
  lordGuj: string;
  yoniEng: string;
  yoniHin: string;
  yoniGuj: string;
  treeEng: string;
  treeHin: string;
  treeGuj: string;
  rashiScopeEng: string;
  rashiScopeHin: string;
  rashiScopeGuj: string;
  element: 'Agni (Fire)' | 'Prithvi (Earth)' | 'Vayu (Air)' | 'Jala (Water)' | 'Akasha (Ether)';
  gana: 'Deva' | 'Manushya' | 'Rakshasa';
  descEng: string;
  descHin: string;
  descGuj: string;
}

export const NAKSHATRA_DETAILS_MAP: Record<number, NakshatraDetailItem> = {
  1: {
    index: 1,
    nameEng: 'Ashwini',
    nameHin: 'अश्विनी',
    nameGuj: 'અશ્વિની',
    symbolEng: "Horse's Head 🐴",
    symbolHin: 'अश्व का सिर 🐴',
    symbolGuj: 'અશ્વનું શિર 🐴',
    deityEng: 'Ashwini Kumaras (Physicians of Devas)',
    deityHin: 'अश्विनी कुमार (देवताओं के वैद्य)',
    deityGuj: 'અશ્વિની કુમારો (દેવોના વૈદ્ય)',
    lordEng: 'Ketu',
    lordHin: 'केतु',
    lordGuj: 'કેતુ',
    yoniEng: 'Male Horse (अश्व / ઘોડો)',
    yoniHin: 'अश्व (घोड़ा)',
    yoniGuj: 'અશ્વ (ઘોડો)',
    treeEng: 'Kuchla / Poison Nut (Strychnos nux-vomica)',
    treeHin: 'कुचला वृक्ष',
    treeGuj: 'ઝેરકોચલું વૃક્ષ',
    rashiScopeEng: "Aries 0°00' - 13°20'",
    rashiScopeHin: "मेष ०°००' - १३°२०'",
    rashiScopeGuj: "મેષ ૦°૦૦' - ૧૩°૨૦'",
    element: 'Agni (Fire)',
    gana: 'Deva',
    descEng: 'Symbolizes swift movement, initiation, healing powers, and pioneering energy.',
    descHin: 'शीघ्र गति, आरोग्य, नवोन्मेष और देव वैद्य ऊर्जा का प्रतीक।',
    descGuj: 'ઝડપી ગતિ, આરોગ્ય અને નવીન કાર્યની શરૂઆતનું પ્રતિક.'
  },
  2: {
    index: 2,
    nameEng: 'Bharani',
    nameHin: 'भरणी',
    nameGuj: 'ભરણી',
    symbolEng: 'Yoni / Sacred Womb 🌸',
    symbolHin: 'योनि / पवित्र गर्भ 🌸',
    symbolGuj: 'યોનિ / પવિત્ર ગર્ભ 🌸',
    deityEng: 'Yama (God of Death & Dharma)',
    deityHin: 'यमराज (धर्म एवं मृत्यु के देवता)',
    deityGuj: 'યમરાજ (ધર્મ અને મૃત્યુના દેવ)',
    lordEng: 'Venus (Shukra)',
    lordHin: 'शुक्र',
    lordGuj: 'શુક્ર',
    yoniEng: 'Female Elephant (हस्तिनी / હાથણી)',
    yoniHin: 'हस्तिनी (हाथी)',
    yoniGuj: 'હસ્તિની (હાથી)',
    treeEng: 'Aonla / Indian Gooseberry (Phyllanthus emblica)',
    treeHin: 'आंवला वृक्ष',
    treeGuj: 'આમળાં વૃક્ષ',
    rashiScopeEng: "Aries 13°20' - 26°40'",
    rashiScopeHin: "मेष १३°२०' - २६°४०'",
    rashiScopeGuj: "મેષ ૧૩°૨૦' - ૨૬°૪૦'",
    element: 'Prithvi (Earth)',
    gana: 'Manushya',
    descEng: 'Governs transformation, endurance, desire, rebirth, and inner restraint.',
    descHin: 'रूपांतरण, सहनशक्ति, कर्म शुद्धता और पुनर्जन्म का प्रतीक।',
    descGuj: 'રૂપાંતરણ, સહનશક્તિ અને પુનર્જન્મ દર્શાવતું નક્ષત્ર.'
  },
  3: {
    index: 3,
    nameEng: 'Krittika',
    nameHin: 'कृत्तिका',
    nameGuj: 'કૃત્તિકા',
    symbolEng: 'Razor / Flame 🗡️🔥',
    symbolHin: 'छुरा / अग्नि ज्वाला 🗡️🔥',
    symbolGuj: 'કટાર / અગ્નિ જ્વાળા 🗡️🔥',
    deityEng: 'Agni (God of Fire & Transformation)',
    deityHin: 'अग्नि देव (पावक एवं शुद्धता)',
    deityGuj: 'અગ્નિ દેવ (પવિત્રતા અને તેજ)',
    lordEng: 'Sun (Surya)',
    lordHin: 'सूर्य',
    lordGuj: 'સૂર્ય',
    yoniEng: 'Female Sheep / Goat (मेष / બકરી)',
    yoniHin: 'मेष (बकरी)',
    yoniGuj: 'મેષ (બકરી)',
    treeEng: 'Gular / Cluster Fig (Ficus racemosa)',
    treeHin: 'गूलर वृक्ष',
    treeGuj: 'ઉમરો વૃક્ષ',
    rashiScopeEng: "Aries 26°40' - Taurus 10°00'",
    rashiScopeHin: "मेष २६°४०' - वृषभ १०°००'",
    rashiScopeGuj: "મેષ ૨૬°૪૦' - વૃષભ ૧૦°૦૦'",
    element: 'Agni (Fire)',
    gana: 'Rakshasa',
    descEng: 'Represents sharp intellect, purification, digestive fire, and decisive action.',
    descHin: 'तीक्ष्ण बुद्धि, पावक शुद्धता और दृढ निर्णय क्षमता।',
    descGuj: 'તીક્ષ્ણ બુદ્ધિ, અગ્નિ પવિત્રતા અને દ્રઢ નિર્ણય શક્તિ.'
  },
  4: {
    index: 4,
    nameEng: 'Rohini',
    nameHin: 'रोहिणी',
    nameGuj: 'રોહિણી',
    symbolEng: 'Chariot / Temple Cart 🛞',
    symbolHin: 'रथ / मंदिर रथ 🛞',
    symbolGuj: 'રથ / દેવ રથ 🛞',
    deityEng: 'Lord Brahma (Prajapati - Creator)',
    deityHin: 'प्रजापति ब्रह्मा (सृष्टि रचयिता)',
    deityGuj: 'પ્રજાપતિ બ્રહ્મા (સૃષ્ટિના સર્જક)',
    lordEng: 'Moon (Chandra)',
    lordHin: 'चंद्र',
    lordGuj: 'ચંદ્ર',
    yoniEng: 'Male Serpent (सर्प / સર્પ)',
    yoniHin: 'सर्प (नाग)',
    yoniGuj: 'સર્પ (નાગ)',
    treeEng: 'Jamun / Black Plum (Syzygium cumini)',
    treeHin: 'जामुन वृक्ष',
    treeGuj: 'જાંબુ વૃક્ષ',
    rashiScopeEng: "Taurus 10°00' - 23°20'",
    rashiScopeHin: "वृषभ १०°००' - २३°२०'",
    rashiScopeGuj: "વૃષભ ૧૦°૦૦' - ૨૩°૨૦'",
    element: 'Prithvi (Earth)',
    gana: 'Manushya',
    descEng: 'Associated with beauty, growth, magnetism, fertility, and artistic abundance.',
    descHin: 'सौंदर्य, विकास, कलात्मक आकर्षण और समृद्धि का सूचक।',
    descGuj: 'સૌંદર્ય, વૃદ્ધિ, કલા અને સમૃદ્ધિનું પ્રતિક.'
  },
  5: {
    index: 5,
    nameEng: 'Mrigashirsha',
    nameHin: 'मृगशिरा',
    nameGuj: 'મૃગશિરા',
    symbolEng: "Deer's Head 🦌",
    symbolHin: 'हिरण का सिर 🦌',
    symbolGuj: 'હરણનું મસ્તક 🦌',
    deityEng: 'Soma (Moon God of Divine Nectar)',
    deityHin: 'सोम देव (अमृत एवं शांति)',
    deityGuj: 'સોમ દેવ (અમૃત અને શાંતિ)',
    lordEng: 'Mars (Mangala)',
    lordHin: 'मंगल',
    lordGuj: 'મંગળ',
    yoniEng: 'Female Serpent (सर्पिणी / નાગણ)',
    yoniHin: 'सर्पिणी',
    yoniGuj: 'સર્પિણી',
    treeEng: 'Khair / Catechu (Senegalia catechu)',
    treeHin: 'खैर वृक्ष',
    treeGuj: 'ખેર વૃક્ષ',
    rashiScopeEng: "Taurus 23°20' - Gemini 6°40'",
    rashiScopeHin: "वृषभ २३°२०' - मिथुन ६°४०'",
    rashiScopeGuj: "વૃષભ ૨૩°૨૦' - મિથુન ૬°૪૦'",
    element: 'Vayu (Air)',
    gana: 'Deva',
    descEng: 'Represents searching, curiosity, gentle quest for truth, and research aptitude.',
    descHin: 'जिज्ञासा, शोध भावना, सत्य की खोज और सौम्य स्वभाव।',
    descGuj: 'જિજ્ઞાસા, સંશોધન વૃત્તિ અને સત્યની શોધીનું પ્રતિક.'
  },
  6: {
    index: 6,
    nameEng: 'Ardra',
    nameHin: 'आर्द्रा',
    nameGuj: 'આર્દ્રા',
    symbolEng: 'Teardrop / Diamond 💧💎',
    symbolHin: 'अश्रु बिंदु / हीरा 💧💎',
    symbolGuj: 'અશ્રુબિંદુ / હીરો 💧💎',
    deityEng: 'Rudra (Fierce Storm God / Shiva)',
    deityHin: 'रुद्र (शिव का उग्र स्वरूप)',
    deityGuj: 'રુદ્ર (શિવનું રુદ્ર સ્વરૂપ)',
    lordEng: 'Rahu',
    lordHin: 'राहु',
    lordGuj: 'રાહુ',
    yoniEng: 'Female Dog (श्वानी / કુતરી)',
    yoniHin: 'श्वानी (कुतिया)',
    yoniGuj: 'શ્વાની (કુતરી)',
    treeEng: 'Agarwood / Long Pepper (Piper longum)',
    treeHin: 'अगर वृक्ष / पिप्पली',
    treeGuj: 'અગર વૃક્ષ / પીપરી',
    rashiScopeEng: "Gemini 6°40' - 20°00'",
    rashiScopeHin: "मिथुन ६°४०' - २०°००'",
    rashiScopeGuj: "મિથુન ૬°૪૦' - ૨૦°૦૦'",
    element: 'Jala (Water)',
    gana: 'Manushya',
    descEng: 'Embodiment of catharsis, intellectual breakthroughs, emotional cleansing, and renewal.',
    descHin: 'भावात्मक शुद्धि, बौधिक क्रांति और नवसृजन का आधार।',
    descGuj: 'ભાવનાત્મક શુદ્ધિ અને નવોદયનું જળતત્વ નક્ષત્ર.'
  },
  7: {
    index: 7,
    nameEng: 'Punarvasu',
    nameHin: 'पुनर्वसु',
    nameGuj: 'પુનર્વસુ',
    symbolEng: 'Quiver of Arrows 🏹',
    symbolHin: 'बाणों का भाथा 🏹',
    symbolGuj: 'બાણનો ભાથો 🏹',
    deityEng: 'Aditi (Cosmic Mother of Devas)',
    deityHin: 'अदिति (देवताओं की माता)',
    deityGuj: 'અદિતિ (દેવોની માતા)',
    lordEng: 'Jupiter (Brihaspati)',
    lordHin: 'गुरु',
    lordGuj: 'ગુરુ',
    yoniEng: 'Female Cat (मार्जारी / બિલાડી)',
    yoniHin: 'मार्जारी (बिल्ली)',
    yoniGuj: 'માર્જારી (બિલાડી)',
    treeEng: 'Bamboo (Bambusa arundinacea)',
    treeHin: 'बांस वृक्ष',
    treeGuj: 'વાંસ વૃક્ષ',
    rashiScopeEng: "Gemini 20°00' - Cancer 3°20'",
    rashiScopeHin: "मिथुन २०°००' - कर्क ३°२०'",
    rashiScopeGuj: "મિથુન ૨૦°૦૦' - કર્ક ૩°૨૦'",
    element: 'Akasha (Ether)',
    gana: 'Deva',
    descEng: 'Signifies return of light, restoration, safety, abundance, and second chances.',
    descHin: 'पुनरागमन, सुरक्षा, पुनः समृद्धि और आशा का संचरण।',
    descGuj: 'પુનરાગમન, આશા અને નવી સમૃદ્ધિ આપતું નક્ષત્ર.'
  },
  8: {
    index: 8,
    nameEng: 'Pushya',
    nameHin: 'पुष्य',
    nameGuj: 'પુષ્ય',
    symbolEng: "Cow's Udder / Lotus 🐄🌸",
    symbolHin: 'गौ थन / कमल पुष्प 🐄🌸',
    symbolGuj: 'ગાયનું આંચળ / કમળ 🐄🌸',
    deityEng: 'Brihaspati (Guru of All Devas)',
    deityHin: 'बृहस्पति (देव गुरु)',
    deityGuj: 'બૃહસ્પતિ (દેવ ગુરુ)',
    lordEng: 'Saturn (Shani)',
    lordHin: 'शनि',
    lordGuj: 'શનિ',
    yoniEng: 'Male Goat (छाग / બકરો)',
    yoniHin: 'छाग (बकरा)',
    yoniGuj: 'છાગ (બકરો)',
    treeEng: 'Peepal / Sacred Fig (Ficus religiosa)',
    treeHin: 'पीपल वृक्ष',
    treeGuj: 'પીપળો વૃક્ષ',
    rashiScopeEng: "Cancer 3°20' - 16°40'",
    rashiScopeHin: "कर्क ३°२०' - १६°४०'",
    rashiScopeGuj: "કર્ક ૩°૨૦' - ૧૬°૪૦'",
    element: 'Jala (Water)',
    gana: 'Deva',
    descEng: 'Most auspicious star for spiritual nourishment, wisdom, stability, and growth.',
    descHin: 'सर्वश्रेष्ठ शुभ नक्षत्र, पोषण, ज्ञान और शाश्वत समृद्धि।',
    descGuj: 'સૌથી કલ્યાણકારી નક્ષત્ર, પોષણ અને જ્ઞાનનો સ્રોત.'
  },
  9: {
    index: 9,
    nameEng: 'Ashlesha',
    nameHin: 'अश्लेषा',
    nameGuj: 'અશ્લેષા',
    symbolEng: 'Coiled Serpent 🐍',
    symbolHin: 'कुंडलित नाग 🐍',
    symbolGuj: 'વીંટળાયેલો સર્પ 🐍',
    deityEng: 'Nagas (Serpent Deities of Wisdom & Kundalini)',
    deityHin: 'नाग देव (कुंडलिनी व गूढ़ विद्या)',
    deityGuj: 'નાગ દેવ (ગુપ્ત વિદ્યા)',
    lordEng: 'Mercury (Budha)',
    lordHin: 'बुध',
    lordGuj: 'બુધ',
    yoniEng: 'Male Cat (मार्जार / બિલાડો)',
    yoniHin: 'मार्जार (बिलाव)',
    yoniGuj: 'માર્જાર (બિલાડો)',
    treeEng: 'Nagkeshar (Mesua ferrea)',
    treeHin: 'नागकेसर वृक्ष',
    treeGuj: 'નાગકેસર વૃક્ષ',
    rashiScopeEng: "Cancer 16°40' - 30°00'",
    rashiScopeHin: "कर्क १६°४०' - ३०°००'",
    rashiScopeGuj: "કર્ક ૧૬°૪૦' - ૩૦°૦૦'",
    element: 'Jala (Water)',
    gana: 'Rakshasa',
    descEng: 'Governs Kundalini energy, hypnotic depth, keen intuition, and protective instinct.',
    descHin: 'गूढ़ विद्या, कुंडलिनी शक्ति, सम्मोहन और गहन अंतर्ज्ञान।',
    descGuj: 'ગુપ્ત વિદ્યા, કુંડલિની શક્તિ અને ઊંડી આંતરદ્રષ્ટિ.'
  },
  10: {
    index: 10,
    nameEng: 'Magha',
    nameHin: 'मघा',
    nameGuj: 'મઘા',
    symbolEng: 'Royal Throne / Palanquin 👑',
    symbolHin: 'राज सिंहासन / पालकी 👑',
    symbolGuj: 'રાજ સિંહાસન / પાલખી 👑',
    deityEng: 'Pitrs (Ancestral Guardian Spirits)',
    deityHin: 'पितृ देव (पूर्वज एवं कुल संरक्षक)',
    deityGuj: 'પિતૃ દેવ (પૂર્વજો)',
    lordEng: 'Ketu',
    lordHin: 'केतु',
    lordGuj: 'કેતુ',
    yoniEng: 'Male Rat (मूषक / ઉંદર)',
    yoniHin: 'मूषक (चूहा)',
    yoniGuj: 'મૂષક (ઉંદર)',
    treeEng: 'Banyan / Bargad (Ficus benghalensis)',
    treeHin: 'बरगद वृक्ष',
    treeGuj: 'વડ વૃક્ષ',
    rashiScopeEng: "Leo 0°00' - 13°20'",
    rashiScopeHin: "सिंह ०°००' - १३°२०'",
    rashiScopeGuj: "સિંહ ૦°૦૦' - ૧૩°૨૦'",
    element: 'Agni (Fire)',
    gana: 'Rakshasa',
    descEng: 'Embodiment of royal lineage, ancestral blessings, authority, and noble pride.',
    descHin: 'शाही गरिमा, पितृ आशीर्वाद, अधिकार और नेतृत्व क्षमता।',
    descGuj: 'શાહી ગૌરવ, પૂર્વજોના આશીર્વાદ અને નેતૃત્વ.'
  },
  11: {
    index: 11,
    nameEng: 'Purva Phalguni',
    nameHin: 'पूर्व फाल्गुनी',
    nameGuj: 'પૂર્વ ફાલ્ગુની',
    symbolEng: 'Front Legs of Bed / Hammock 🛋️',
    symbolHin: 'झूला / शय्या के आगे के पाये 🛋️',
    symbolGuj: 'હીંચકો / ખાટલાના આગળના પાયા 🛋️',
    deityEng: 'Bhaga (God of Marital Happiness & Prosperity)',
    deityHin: 'भग देव (वैवाहिक सुख व ऐश्वर्य)',
    deityGuj: 'ભગ દેવ (દામ્પત્ય સુખ અને વૈભવ)',
    lordEng: 'Venus (Shukra)',
    lordHin: 'शुक्र',
    lordGuj: 'શુક્ર',
    yoniEng: 'Female Rat (मूषिका / ઉંદરડી)',
    yoniHin: 'मूषिका (चूहिया)',
    yoniGuj: 'મૂષિકા (ઉંદરડી)',
    treeEng: 'Palash / Flame of Forest (Butea monosperma)',
    treeHin: 'पलाश वृक्ष (ढाक)',
    treeGuj: 'ખાખરો વૃક્ષ',
    rashiScopeEng: "Leo 13°20' - 26°40'",
    rashiScopeHin: "सिंह १३°२०' - २६°४०'",
    rashiScopeGuj: "સિંહ ૧૩°૨૦' - ૨૬°૪૦'",
    element: 'Jala (Water)',
    gana: 'Manushya',
    descEng: 'Associated with relaxation, creative arts, romantic bliss, and comfortable luxury.',
    descHin: 'आनंद, विश्राम, कलात्मक रचनात्मकता और दांपत्य सुख।',
    descGuj: 'આનંદ, વિશ્રામ, કલાત્મકતા અને દામ્પત્ય સુખ.'
  },
  12: {
    index: 12,
    nameEng: 'Uttara Phalguni',
    nameHin: 'उत्तर फाल्गुनी',
    nameGuj: 'ઉત્તર ફાલ્ગુની',
    symbolEng: 'Back Legs of Bed 🛏️',
    symbolHin: 'शय्या के पीछे के पाये 🛏️',
    symbolGuj: 'ખાટલાના પાછળના પાયા 🛏️',
    deityEng: 'Aryaman (God of Patronage & Alliances)',
    deityHin: 'अर्यमा (मित्रता व संधि के देवता)',
    deityGuj: 'અર્યમા (મિત્રતા અને સગાઈના દેવ)',
    lordEng: 'Sun (Surya)',
    lordHin: 'सूर्य',
    lordGuj: 'સૂર્ય',
    yoniEng: 'Bull (वृषभ / બળદ)',
    yoniHin: 'वृषभ (बैल)',
    yoniGuj: 'વૃષભ (બળદ)',
    treeEng: 'Pakar / White Fig (Ficus virens)',
    treeHin: 'पाकड़ वृक्ष',
    treeGuj: 'પીપળ વૃક્ષ',
    rashiScopeEng: "Leo 26°40' - Virgo 10°00'",
    rashiScopeHin: "सिंह २६°४०' - कन्या १०°००'",
    rashiScopeGuj: "સિંહ ૨૬°૪૦' - કન્યા ૧૦°૦૦'",
    element: 'Agni (Fire)',
    gana: 'Manushya',
    descEng: 'Promotes enduring relationships, generosity, philanthropic duty, and social honor.',
    descHin: 'दीर्घकालीन संबंध, दानशीलता, सामाजिक कर्तव्य और सम्मान।',
    descGuj: 'લાંબા ગાળાના સંબંધો, ઉદારતા અને સામાજિક સન્માન.'
  },
  13: {
    index: 13,
    nameEng: 'Hasta',
    nameHin: 'हस्त',
    nameGuj: 'હસ્ત',
    symbolEng: 'Open Hand / Fist 🖐️',
    symbolHin: 'खुली हथेली / मुट्ठी 🖐️',
    symbolGuj: 'ખુલ્લો હાથ / મુઠ્ઠી 🖐️',
    deityEng: 'Savitr (Solar Deity of Dawn & Craftsmanship)',
    deityHin: 'सवितृ (सविता सूर्य देव)',
    deityGuj: 'સવિતૃ (સૂર્ય દેવ)',
    lordEng: 'Moon (Chandra)',
    lordHin: 'चंद्र',
    lordGuj: 'ચંદ્ર',
    yoniEng: 'Female Buffalo (महिषी / ભેંસ)',
    yoniHin: 'महिषी (भैंस)',
    yoniGuj: 'મહિષી (ભેંસ)',
    treeEng: 'Rita / Wild Jasmine (Jasminum grandiflorum)',
    treeHin: 'रीठा / चमेली',
    treeGuj: 'અસોપાલવ / ચમેલી',
    rashiScopeEng: "Virgo 10°00' - 23°20'",
    rashiScopeHin: "कन्या १०°००' - २३°२०'",
    rashiScopeGuj: "કન્યા ૧૦°૦૦' - ૨૩°૨૦'",
    element: 'Vayu (Air)',
    gana: 'Deva',
    descEng: 'Symbolizes dexterity, healing touch, astrology, craftsmanship, and mental agility.',
    descHin: 'हस्त कला, निपुणता, ज्योतिष ज्ञान और व्यावहारिक चातुर्य।',
    descGuj: 'હસ્તકળા, નિપુણતા, જ્યોતિષ જ્ઞાન અને કૌશલ્ય.'
  },
  14: {
    index: 14,
    nameEng: 'Chitra',
    nameHin: 'चित्रा',
    nameGuj: 'ચિત્રા',
    symbolEng: 'Bright Pearl / Gem 💎',
    symbolHin: 'उज्ज्वल रत्न / मोती 💎',
    symbolGuj: 'ઝળહળતો મોતી / રત્ન 💎',
    deityEng: 'Vishwakarma (Divine Architect)',
    deityHin: 'विश्वकर्मा (देव शिल्पी)',
    deityGuj: 'વિશ્વકર્મા (દેવ શિલ્પી)',
    lordEng: 'Mars (Mangala)',
    lordHin: 'मंगल',
    lordGuj: 'મંગળ',
    yoniEng: 'Female Tiger (व्याघ्री / વાઘણ)',
    yoniHin: 'व्याघ्री (बाघिन)',
    yoniGuj: 'વ્યાઘ્રી (વાઘણ)',
    treeEng: 'Bel / Wood Apple (Aegle marmelos)',
    treeHin: 'बेल वृक्ष (बिल्व)',
    treeGuj: 'બીલી વૃક્ષ',
    rashiScopeEng: "Virgo 23°20' - Libra 6°40'",
    rashiScopeHin: "कन्या २३°२०' - तुला ६°४०'",
    rashiScopeGuj: "કન્યા ૨૩°૨૦' - તુલા ૬°૪૦'",
    element: 'Agni (Fire)',
    gana: 'Rakshasa',
    descEng: 'Represents architectural beauty, visual elegance, design mastery, and charisma.',
    descHin: 'वास्तु कला, रूप सौंदर्य, डिजाइन कौशल और आकर्षक व्यक्तित्व।',
    descGuj: 'વાસ્તુ કળા, સુંદરતા અને ડિઝાઈન ક્ષમતાનું પ્રતિક.'
  },
  15: {
    index: 15,
    nameEng: 'Swati',
    nameHin: 'स्वाती',
    nameGuj: 'સ્વાતી',
    symbolEng: 'Young Sprout / Sword 🌱⚔️',
    symbolHin: 'कोमल अंकुर / खड्ग 🌱⚔️',
    symbolGuj: 'કોમળ કૂંપળ / તલવાર 🌱⚔️',
    deityEng: 'Vayu (God of Wind & Life Breath)',
    deityHin: 'वायु देव (पवन एवं प्राण)',
    deityGuj: 'વાયુ દેવ (પવન અને પ્રાણ)',
    lordEng: 'Rahu',
    lordHin: 'राहु',
    lordGuj: 'રાહુ',
    yoniEng: 'Male Buffalo (महिष / પાડો)',
    yoniHin: 'महिष (भैंसा)',
    yoniGuj: 'મહિષ (પાડો)',
    treeEng: 'Arjun / Terminalia (Terminalia arjuna)',
    treeHin: 'अर्जुन वृक्ष',
    treeGuj: 'અર્જુન વૃક્ષ',
    rashiScopeEng: "Libra 6°40' - 20°00'",
    rashiScopeHin: "तुला ६°४०' - २०°००'",
    rashiScopeGuj: "તુલા ૬°૪૦' - ૨૦°૦૦'",
    element: 'Vayu (Air)',
    gana: 'Deva',
    descEng: 'Signifies independence, flexibility, diplomatic communication, and business acumen.',
    descHin: 'स्वतंत्रता, लचीलापन, व्यापार चातुर्य और कूटनीतिक संवाद।',
    descGuj: 'સ્વતંત્રતા, વેપાર કુશળતા અને મુક્ત વિચારો.'
  },
  16: {
    index: 16,
    nameEng: 'Vishakha',
    nameHin: 'विशाखा',
    nameGuj: 'વિશાખા',
    symbolEng: 'Triumphal Arch / Potter Wheel 🏛️',
    symbolHin: 'विजय तोरण / कुम्हार का चाक 🏛️',
    symbolGuj: 'વિજય તોરણ / કુંભારનો ચાક 🏛️',
    deityEng: 'Indra-Agni (Alliance of Power & Fire)',
    deityHin: 'इंद्र-अग्नि देव (तेज व सत्ता का योग)',
    deityGuj: 'ઇન્દ્ર-અગ્નિ દેવ (તેજ અને સત્તા)',
    lordEng: 'Jupiter (Brihaspati)',
    lordHin: 'गुरु',
    lordGuj: 'ગુરુ',
    yoniEng: 'Male Tiger (व्याघ्र / વાઘ)',
    yoniHin: 'व्याघ्र (बाघ)',
    yoniGuj: 'વ્યાઘ્ર (વાઘ)',
    treeEng: 'Nagkeshar / Red Lotus (Mesua ferrea)',
    treeHin: 'विकंकत / नागकेसर',
    treeGuj: 'નાગકેસર વૃક્ષ',
    rashiScopeEng: "Libra 20°00' - Scorpio 3°20'",
    rashiScopeHin: "तुला २०°००' - वृश्चिक ३°२०'",
    rashiScopeGuj: "તુલા ૨૦°૦૦' - વૃશ્ચિક ૩°૨૦'",
    element: 'Agni (Fire)',
    gana: 'Rakshasa',
    descEng: 'Governs targeted focus, relentless goal achievement, ambition, and victory.',
    descHin: 'लक्ष्य भेद, एकाग्रता, अदम्य महत्वाकांक्षा और विजय की प्राप्ति।',
    descGuj: 'ધ્યેય પ્રાપ્તિ, એકાગ્રતા અને અદમ્ય વિજય મેળવવાની શક્તિ.'
  },
  17: {
    index: 17,
    nameEng: 'Anuradha',
    nameHin: 'अनुराधा',
    nameGuj: 'અનુરાધા',
    symbolEng: 'Lotus Flower / Staff 🪷',
    symbolHin: 'कमल पुष्प / दंड 🪷',
    symbolGuj: 'કમળનું ફૂલ / દંડ 🪷',
    deityEng: 'Mitra (God of Divine Friendship & Union)',
    deityHin: 'मित्र देव (मैत्री व सौहार्द)',
    deityGuj: 'મિત્ર દેવ (મિત્રતા અને સદ્ભાવ)',
    lordEng: 'Saturn (Shani)',
    lordHin: 'शनि',
    lordGuj: 'શનિ',
    yoniEng: 'Female Deer (मृगी / હરણી)',
    yoniHin: 'मृगी (हिरणी)',
    yoniGuj: 'મૃગી (હરણી)',
    treeEng: 'Moulshree / Bakul (Mimusops elengi)',
    treeHin: 'बकुल वृक्ष (मौलश्री)',
    treeGuj: 'બોરસલ્લી વૃક્ષ',
    rashiScopeEng: "Scorpio 3°20' - 16°40'",
    rashiScopeHin: "वृश्चिक ३°२०' - १६°४०'",
    rashiScopeGuj: "વૃશ્ચિક ૩°૨૦' - ૧૬°૪૦'",
    element: 'Agni (Fire)',
    gana: 'Deva',
    descEng: 'Represents organizational ability, loyal friendship, devotion, and travel.',
    descHin: 'संगठन क्षमता, निष्ठावान मित्रता, भक्ति भाव और विदेश यात्रा।',
    descGuj: 'સંગઠન શક્તિ, સચ્ચી મિત્રતા અને ભક્તિભાવ.'
  },
  18: {
    index: 18,
    nameEng: 'Jyeshtha',
    nameHin: 'ज्येष्ठा',
    nameGuj: 'જ્યેષ્ઠા',
    symbolEng: 'Circular Earring / Umbrella ☂️',
    symbolHin: 'छत्र / कुंडल तावीज ☂️',
    symbolGuj: 'છત્ર / કુંડળ તાવીજ ☂️',
    deityEng: 'Indra (King of Devas & Thunderbolts)',
    deityHin: 'देवराज इंद्र (सुरेश व शक्ति)',
    deityGuj: 'દેવરાજ ઇન્દ્ર (સુરેશ અને શક્તિ)',
    lordEng: 'Mercury (Budha)',
    lordHin: 'बुध',
    lordGuj: 'બુધ',
    yoniEng: 'Male Deer (मृग / હરણ)',
    yoniHin: 'मृग (हिरण)',
    yoniGuj: 'મૃગ (હરણ)',
    treeEng: 'Neem / Cheeta (Azadirachta indica)',
    treeHin: 'चीता / नीम वृक्ष',
    treeGuj: 'લીમડો વૃક્ષ',
    rashiScopeEng: "Scorpio 16°40' - 30°00'",
    rashiScopeHin: "वृश्चिक १६°४०' - ३०°००'",
    rashiScopeGuj: "વૃશ્ચિક ૧૬°૪૦' - ૩૦°૦૦'",
    element: 'Vayu (Air)',
    gana: 'Rakshasa',
    descEng: 'Symbolizes seniority, protective authority, heroic courage, and spiritual mastery.',
    descHin: 'ज्येष्ठता, रक्षात्मक अधिकार, शौर्य और आध्यात्मिक परिपक्वता।',
    descGuj: 'વરિષ્ઠતા, રક્ષણ કરવાની ક્ષમતા અને આત્મવિશ્વાસ.'
  },
  19: {
    index: 19,
    nameEng: 'Mula',
    nameHin: 'मूल',
    nameGuj: 'મૂળ',
    symbolEng: 'Tied Bunch of Roots 🪵',
    symbolHin: 'मूल जड़ें / गुच्छा 🪵',
    symbolGuj: 'મૂળનો જથ્થો 🪵',
    deityEng: 'Nirriti (Goddess of Transformation & Roots)',
    deityHin: 'निरृति (महाकाली व रूपांतरण देवी)',
    deityGuj: 'નિરૃતિ (રૂપાંતરણ દેવી)',
    lordEng: 'Ketu',
    lordHin: 'केतु',
    lordGuj: 'કેતુ',
    yoniEng: 'Male Dog (श्वान / કુતરો)',
    yoniHin: 'श्वान (कुत्ता)',
    yoniGuj: 'શ્વાન (કુતરો)',
    treeEng: 'Sal / Rala (Shorea robusta)',
    treeHin: 'शाल वृक्ष',
    treeGuj: 'સાલ વૃક્ષ',
    rashiScopeEng: "Sagittarius 0°00' - 13°20'",
    rashiScopeHin: "धनु ०°००' - १३°२०'",
    rashiScopeGuj: "ધનુ ૦°૦૦' - ૧૩°૨૦'",
    element: 'Prithvi (Earth)',
    gana: 'Rakshasa',
    descEng: 'Governs root causes, radical research, breaking illusions, and spiritual foundation.',
    descHin: 'मूल कारण शोध, भ्रम निवारण और आध्यात्मिक गहराई।',
    descGuj: 'મૂળ કારણની શોધ, ઊંડું સંશોધન અને આધ્યાત્મિકતા.'
  },
  20: {
    index: 20,
    nameEng: 'Purva Ashadha',
    nameHin: 'पूर्वाषाढा',
    nameGuj: 'પૂર્વાષાઢા',
    symbolEng: 'Winnowing Basket / Elephant Tusk 🌾',
    symbolHin: 'सूप / हाथी का दांत 🌾',
    symbolGuj: 'સૂપડું / દંતશૂળ 🌾',
    deityEng: 'Apas (Cosmic Water Goddesses)',
    deityHin: 'अपः (जल देवियाँ व शुद्धता)',
    deityGuj: 'અપઃ (જળ દેવીઓ)',
    lordEng: 'Venus (Shukra)',
    lordHin: 'शुक्र',
    lordGuj: 'શુક્ર',
    yoniEng: 'Male Monkey (वानर / વાંદરો)',
    yoniHin: 'वानर (बंदर)',
    yoniGuj: 'વાનર (વાંદરો)',
    treeEng: 'Ashoka Tree (Saraca asoca)',
    treeHin: 'अशोक वृक्ष',
    treeGuj: 'અશોક વૃક્ષ',
    rashiScopeEng: "Sagittarius 13°20' - 26°40'",
    rashiScopeHin: "धनु १३°२०' - २६°४०'",
    rashiScopeGuj: "ધનુ ૧૩°૨૦' - ૨૬°૪૦'",
    element: 'Jala (Water)',
    gana: 'Manushya',
    descEng: 'Represents invincibility, emotional purification, eloquence, and victory over trials.',
    descHin: 'अपराजिता भाव, जल शुद्धता, ओजस्वी वाक् शक्ति और विजय।',
    descGuj: 'અપરાજય શક્તિ, વાકપટુતા અને વિજયી ભાવ.'
  },
  21: {
    index: 21,
    nameEng: 'Uttara Ashadha',
    nameHin: 'उत्तराषाढा',
    nameGuj: 'ઉત્તરાષાઢા',
    symbolEng: 'Elephant Tusk / Small Bed 🐘',
    symbolHin: 'गज दंत / लघु शय्या 🐘',
    symbolGuj: 'હાથીનો દાંત / શય્યા 🐘',
    deityEng: 'Vishwadevas (Ten Cosmic Deities of Universal Truth)',
    deityHin: 'विश्वेदेव (दश सार्वभौमिक देव)',
    deityGuj: 'વિશ્વેદેવ (દસ સાર્વભૌમિક દેવ)',
    lordEng: 'Sun (Surya)',
    lordHin: 'सूर्य',
    lordGuj: 'સૂર્ય',
    yoniEng: 'Mongoose (नकुल / નોળિયો)',
    yoniHin: 'नकुल (नेवला)',
    yoniGuj: 'નકુલ (નોળિયો)',
    treeEng: 'Jackfruit / Katahar (Artocarpus heterophyllus)',
    treeHin: 'कटहल वृक्ष',
    treeGuj: 'ફણસ વૃક્ષ',
    rashiScopeEng: "Sagittarius 26°40' - Capricorn 10°00'",
    rashiScopeHin: "धनु २६°४०' - मकर १०°००'",
    rashiScopeGuj: "ધનુ ૨૬°૪૦' - મકર ૧૦°૦૦'",
    element: 'Agni (Fire)',
    gana: 'Manushya',
    descEng: 'Symbolizes permanent victory, righteousness, universal responsibility, and duty.',
    descHin: 'स्थायी विजय, धर्मनिष्ठा, सार्वभौमिक उत्तरदायित्व।',
    descGuj: 'શાશ્વત વિજય, ધર્મનિષ્ઠા અને સામાજિક જવાબદારી.'
  },
  22: {
    index: 22,
    nameEng: 'Shravana',
    nameHin: 'श्रवण',
    nameGuj: 'શ્રવણ',
    symbolEng: 'Three Footprints / Human Ear 👣👂',
    symbolHin: 'त्रिपद चिन्ह / कर्ण 👣👂',
    symbolGuj: 'ત્રણ પગલાં / કાન 👣👂',
    deityEng: 'Lord Vishnu (Preserver of Universe)',
    deityHin: 'भगवान श्री हरि विष्णु (पालक देव)',
    deityGuj: 'ભગવાન શ્રી હરિ વિષ્ણુ (પાલક દેવ)',
    lordEng: 'Moon (Chandra)',
    lordHin: 'चंद्र',
    lordGuj: 'ચંદ્ર',
    yoniEng: 'Female Monkey (वानरी / વાંદરી)',
    yoniHin: 'वानरी (बंदरी)',
    yoniGuj: 'વાનરી (વાંદરી)',
    treeEng: 'Madaar / Crown Flower (Calotropis gigantea)',
    treeHin: 'मदार वृक्ष (आंकड़ा)',
    treeGuj: 'આંકડો વૃક્ષ',
    rashiScopeEng: "Capricorn 10°00' - 23°20'",
    rashiScopeHin: "मकर १०°००' - २३°२०'",
    rashiScopeGuj: "મકર ૧૦°૦૦' - ૨૩°૨૦'",
    element: 'Vayu (Air)',
    gana: 'Deva',
    descEng: 'Embodiment of active listening, oral tradition, Vedic wisdom, and sacred learning.',
    descHin: 'श्रवण शक्ति, मौखिक ज्ञान परंपरा, वेद विद्या और एकाग्रता।',
    descGuj: 'સાંભળવાની શક્તિ, વેદ જ્ઞાન અને પવિત્ર શ્રવણ.'
  },
  23: {
    index: 23,
    nameEng: 'Dhanishta',
    nameHin: 'धनिष्ठा',
    nameGuj: 'ધનિષ્ઠા',
    symbolEng: 'Drum (Mridangam) / Flute 🥁🪈',
    symbolHin: 'डमरू / मृदंग 🥁🪈',
    symbolGuj: 'ઢોલક / ડમરૂ 🥁🪈',
    deityEng: 'Eight Vasus (Deities of Elemental Abundance)',
    deityHin: 'अष्ट वसु (समृद्धि व प्रकाश देव)',
    deityGuj: 'અષ્ટ વસુ (સમૃદ્ધિના દેવ)',
    lordEng: 'Mars (Mangala)',
    lordHin: 'मंगल',
    lordGuj: 'મંગળ',
    yoniEng: 'Female Lion (सिंही / સિંહણ)',
    yoniHin: 'सिंही (शेरनी)',
    yoniGuj: 'સિંહી (સિંહણ)',
    treeEng: 'Shami / Banni (Prosopis cineraria)',
    treeHin: 'शमी वृक्ष (खेजड़ी)',
    treeGuj: 'ખીજડો વૃક્ષ',
    rashiScopeEng: "Capricorn 23°20' - Aquarius 6°40'",
    rashiScopeHin: "मकर २३°२०' - कुंभ ६°४०'",
    rashiScopeGuj: "મકર ૨૩°૨૦' - કુંભ ૬°૪૦'",
    element: 'Agni (Fire)',
    gana: 'Rakshasa',
    descEng: 'Associated with musical rhythm, wealth, fame, group accomplishments, and optimism.',
    descHin: 'संगीत ताल, प्रचुर धन, कीर्ति और सामूहिक सफलता।',
    descGuj: 'સંગીત લય, પ્રચુર ધન અને સામાજિક પ્રતિષ્ઠા.'
  },
  24: {
    index: 24,
    nameEng: 'Shatabhisha',
    nameHin: 'शतभिषा',
    nameGuj: 'શતભિષા',
    symbolEng: 'Empty Circle / 100 Healers ⭕🩺',
    symbolHin: 'शून्य वृत्त / सौ चिकित्सक ⭕🩺',
    symbolGuj: 'વર્તુળ / સો વૈદ્ય ⭕🩺',
    deityEng: 'Varuna (God of Celestial Waters & Cosmic Law)',
    deityHin: 'वरुण देव (जलपति व ऋत संरक्षक)',
    deityGuj: 'વરુણ દેવ (જળ અને બ્રહ્માંડ નિયમ)',
    lordEng: 'Rahu',
    lordHin: 'राहु',
    lordGuj: 'રાહુ',
    yoniEng: 'Female Horse (अश्विनी / ઘોડી)',
    yoniHin: 'अश्विनी (घोड़ी)',
    yoniGuj: 'અશ્વિની (ઘોડી)',
    treeEng: 'Kadam / Kadamba (Neolamarckia cadamba)',
    treeHin: 'कदम्ब वृक्ष',
    treeGuj: 'કદંબ વૃક્ષ',
    rashiScopeEng: "Aquarius 6°40' - 20°00'",
    rashiScopeHin: "कुंभ ६°४०' - २०°००'",
    rashiScopeGuj: "કુંભ ૬°૪૦' - ૨૦°૦૦'",
    element: 'Jala (Water)',
    gana: 'Rakshasa',
    descEng: 'Governs alternative healing, mysticism, secrecy, cosmic order, and scientific research.',
    descHin: 'सौ वैद्यों की चिकित्सा शक्ति, रहस्य ज्ञान और वैज्ञानिक शोध।',
    descGuj: 'ચિકિત્સા શક્તિ, ગૂઢ વિજ્ઞાન અને સંશોધન.'
  },
  25: {
    index: 25,
    nameEng: 'Purva Bhadrapada',
    nameHin: 'पूर्व भाद्रपद',
    nameGuj: 'પૂર્વ ભાદ્રપદ',
    symbolEng: 'Two Swords / Front Funeral Cot ⚔️',
    symbolHin: 'द्वि-धारी खड्ग / शय्या ⚔️',
    symbolGuj: 'બેધારી તલવાર / શય્યા ⚔️',
    deityEng: 'Aja Ekapada (One-Footed Cosmic Shiva)',
    deityHin: 'अज एकपाद (एकाग्र रुद्र स्वरूप)',
    deityGuj: 'અજ એકપાદ (રુદ્ર સ્વરૂપ)',
    lordEng: 'Jupiter (Brihaspati)',
    lordHin: 'गुरु',
    lordGuj: 'ગુરુ',
    yoniEng: 'Male Lion (सिंह / સિંહ)',
    yoniHin: 'सिंह (शेर)',
    yoniGuj: 'સિંહ',
    treeEng: 'Mango / Aam (Mangifera indica)',
    treeHin: 'आम्र वृक्ष',
    treeGuj: 'કેરીનું વૃક્ષ',
    rashiScopeEng: "Aquarius 20°00' - Pisces 3°20'",
    rashiScopeHin: "कुंभ २०°००' - मीन ३°२०'",
    rashiScopeGuj: "કુંભ २०°૦૦' - મીન ૩°૨૦'",
    element: 'Agni (Fire)',
    gana: 'Manushya',
    descEng: 'Represents intense tapas, spiritual passion, radical transformation, and idealism.',
    descHin: 'उग्र तपस्या, आध्यात्मिक ज्वाला, क्रांति और आदर्शवाद।',
    descGuj: 'તીવ્ર તપસ્યા, ક્રાંતિ અને આધ્યાત્મિક જ્વાળા.'
  },
  26: {
    index: 26,
    nameEng: 'Uttara Bhadrapada',
    nameHin: 'उत्तर भाद्रपद',
    nameGuj: 'ઉત્તર ભાદ્રપદ',
    symbolEng: 'Twin Boys / Back Funeral Cot 👥',
    symbolHin: 'युगल शिशु / अंतिम शय्या 👥',
    symbolGuj: 'જોડકા બાળકો / શય્યા 👥',
    deityEng: 'Ahirbudhnya (Serpent of the Cosmic Depths)',
    deityHin: 'अहिर्बुध्न्य (समुद्र गभीरता के नाग)',
    deityGuj: 'અહિર્બુધ્ન્ય (સમુદ્રના નાગ)',
    lordEng: 'Saturn (Shani)',
    lordHin: 'शनि',
    lordGuj: 'શનિ',
    yoniEng: 'Female Cow (गौ / ગાય)',
    yoniHin: 'गौ (गाय)',
    yoniGuj: 'ગાય',
    treeEng: 'Neem (Azadirachta indica)',
    treeHin: 'नीम वृक्ष',
    treeGuj: 'લીમડો વૃક્ષ',
    rashiScopeEng: "Pisces 3°20' - 16°40'",
    rashiScopeHin: "मीन ३°२०' - १६°४०'",
    rashiScopeGuj: "મીન ૩°૨૦' - ૧૬°૪૦'",
    element: 'Jala (Water)',
    gana: 'Manushya',
    descEng: 'Associated with deep meditation, restraint, wisdom, Kundalini awakening, and peace.',
    descHin: 'गहन ध्यान, संयम, परम शांति और कुंडलिनी जागृति।',
    descGuj: 'ઊંડું ધ્યાન, સંયમ, પરમ શાંતિ અને જ્ઞાન.'
  },
  27: {
    index: 27,
    nameEng: 'Revati',
    nameHin: 'रेवती',
    nameGuj: 'રેવતી',
    symbolEng: 'Pair of Fish / Drum 🐟🥁',
    symbolHin: 'मीन युगल / मृदंग 🐟🥁',
    symbolGuj: 'માછલીની જોડી / મૃદંગ 🐟🥁',
    deityEng: 'Pushan (Protector of Travelers & Souls)',
    deityHin: 'पूषा देव (पथ प्रदर्शक व पशु रक्षक)',
    deityGuj: 'पूષા દેવ (માર્ગદર્શક અને પશુ રક્ષક)',
    lordEng: 'Mercury (Budha)',
    lordHin: 'बुध',
    lordGuj: 'બુધ',
    yoniEng: 'Female Elephant (हस्तिनी / હાથણી)',
    yoniHin: 'हस्तिनी (हाथी)',
    yoniGuj: 'હસ્તિની (હાથી)',
    treeEng: 'Mahua / Indian Butter Tree (Madhuca longifolia)',
    treeHin: 'महुआ वृक्ष',
    treeGuj: 'મહુડો વૃક્ષ',
    rashiScopeEng: "Pisces 16°40' - 30°00'",
    rashiScopeHin: "मीन १६°४०' - ३०°००'",
    rashiScopeGuj: "મીન ૧૬°૪૦' - ૩૦°૦૦'",
    element: 'Akasha (Ether)',
    gana: 'Deva',
    descEng: 'Final Nakshatra symbolizing completion, divine protection, nourishment, and liberation.',
    descHin: 'अंतिम नक्षत्र, पूर्णता, सर्वमंगल कल्याण और मोक्ष मार्ग।',
    descGuj: 'અંતિમ નક્ષત્ર, પૂર્ણતા, કલ્યાણ અને મોક્ષનું દ્વાર.'
  }
};

export function getNakshatraDetail(idx: number): NakshatraDetailItem {
  const safeIdx = Math.min(27, Math.max(1, idx));
  return NAKSHATRA_DETAILS_MAP[safeIdx] || NAKSHATRA_DETAILS_MAP[1];
}
