import { RashiDetail } from '../types/panchang';

export const RASHIPHAL_DATA: RashiDetail[] = [
  {
    id: 'mesha',
    name: 'Aries (Mesha)',
    hindiName: 'मेष (Aries)',
    symbol: '♈',
    element: 'Fire (अग्नि)',
    rulingPlanet: 'Mars (Mangal)',
    dailyPrediction: 'A highly energetic day for strategic decision making and leadership initiatives. Mars grants high courage and clarity.',
    predictionHindi: 'आज का दिन रणनीतिक निर्णय लेने और नेतृत्व क्षमता के लिए अत्यधिक ऊर्जावान और फलदायी है।',
    careerPrediction: '💼 Excellent time for executing pending project launches or pitching new ideas. Senior executives will appreciate your proactive drive.',
    financePrediction: '💰 Financial inflows from past investments are likely. Avoid impulsive speculative trading in late afternoon.',
    lovePrediction: '❤️ Passionate vibes in relationships. Single Aries may connect with someone inspiring through work or mutual friends.',
    healthPrediction: '🩺 High physical stamina, but stay hydrated and avoid overexertion during midday hours.',
    luckyNumber: 9,
    luckyColorName: 'Crimson Red (गहरा लाल)',
    luckyColorHex: '#D32F2F',
    luckyDirection: 'East (पूर्व)',
    auspiciousTimeWindow: '08:15 AM - 10:30 AM',
    dailyRemedy: '🌸 Offer red flowers or Hanuman Chalisa recitation to Mangal Dev for smooth obstacle clearance.',
    compatibility: 'Leo, Sagittarius'
  },
  {
    id: 'vrishabha',
    name: 'Taurus (Vrishabha)',
    hindiName: 'वृषभ (Taurus)',
    symbol: '♉',
    element: 'Earth (पृथ्वी)',
    rulingPlanet: 'Venus (Shukra)',
    dailyPrediction: 'Focus on family harmony, creative endeavors, and financial stability. Venus brings charm and aesthetic peace.',
    predictionHindi: 'पारिवारिक सौहार्द, कलात्मक कार्यों और वित्तीय स्थिरता पर ध्यान केंद्रित करें।',
    careerPrediction: '💼 Creative and design pursuits receive strong acclaim. Collaboration with colleagues brings rewarding results.',
    financePrediction: '💰 Good day for long-term real estate or fixed wealth planning. Unexpected monetary gifts or returns indicated.',
    lovePrediction: '❤️ Warm and supportive atmosphere at home. Expressing affection openly will deepen mutual trust.',
    healthPrediction: '🩺 Mental calm and steady energy. Incorporate light evening walks and wholesome home meals.',
    luckyNumber: 6,
    luckyColorName: 'Amber Gold (सुनहरा पीला)',
    luckyColorHex: '#FFB300',
    luckyDirection: 'South-East (दक्षिण-पूर्व)',
    auspiciousTimeWindow: '10:45 AM - 12:30 PM',
    dailyRemedy: '🪔 Light a ghee lamp in the evening and recite "Om Shukraya Namah" for prosperity.',
    compatibility: 'Virgo, Capricorn'
  },
  {
    id: 'mithuna',
    name: 'Gemini (Mithuna)',
    hindiName: 'मिथुन (Gemini)',
    symbol: '♊',
    element: 'Air (वायु)',
    rulingPlanet: 'Mercury (Budha)',
    dailyPrediction: 'Exceptional communication and analytical intellect open new doors in business contracts and media.',
    predictionHindi: 'उत्कृष्ट संवाद क्षमता और बौद्धिक कौशल से व्यापार और अनुबंधों में नए अवसर प्राप्त होंगे।',
    careerPrediction: '💼 Perfect day for negotiations, writing, coding, and presentations. Your sharp logic wins team support.',
    financePrediction: '💰 Favorable for short-term financial gains and business agreements. Review documents carefully before signing.',
    lovePrediction: '❤️ Intellectual conversations stimulate deep bond. Great day for joint travel planning.',
    healthPrediction: '🩺 Mind is active; practice 10 minutes of deep breathing (Pranayama) to prevent mental fatigue.',
    luckyNumber: 5,
    luckyColorName: 'Emerald Green (पन्ना हरा)',
    luckyColorHex: '#388E3C',
    luckyDirection: 'North (उत्तर)',
    auspiciousTimeWindow: '02:00 PM - 03:45 PM',
    dailyRemedy: '🌿 Feed green grass (Durva) to cows or offer green gram (Moong) to honor Lord Budha.',
    compatibility: 'Libra, Aquarius'
  },
  {
    id: 'karka',
    name: 'Cancer (Karka)',
    hindiName: 'कर्क (Cancer)',
    symbol: '♋',
    element: 'Water (जल)',
    rulingPlanet: 'Moon (Chandra)',
    dailyPrediction: 'Emotional intuition is heightened. Trust your inner voice in personal and financial matters.',
    predictionHindi: 'भावनात्मक अंतर्दृष्टि मजबूत रहेगी। व्यक्तिगत और वित्तीय मामलों में अंतरात्मा की आवाज पर भरोसा करें।',
    careerPrediction: '💼 Empathetic leadership boosts team morale. Focus on completing ongoing responsibilities with care.',
    financePrediction: '💰 Stable financial growth. Savings strategies implemented today yield long-term peace of mind.',
    lovePrediction: '❤️ Deep emotional intimacy and understanding with your partner. Family blessings bring joy.',
    healthPrediction: '🩺 Hydration and restful sleep are essential. Evening meditation brings deep rejuvenation.',
    luckyNumber: 2,
    luckyColorName: 'Pearl White (मोती सफेद)',
    luckyColorHex: '#F5F5F5',
    luckyDirection: 'North-West (उत्तर-पश्चिम)',
    auspiciousTimeWindow: '07:00 AM - 08:45 AM',
    dailyRemedy: '🥛 Offer milk or Arghya to the Moon at night for emotional peace and mental strength.',
    compatibility: 'Scorpio, Pisces'
  },
  {
    id: 'simha',
    name: 'Leo (Simha)',
    hindiName: 'सिंह (Leo)',
    symbol: '♌',
    element: 'Fire (अग्नि)',
    rulingPlanet: 'Sun (Surya)',
    dailyPrediction: 'Radiant confidence and natural authority attract recognition and success in high-visibility tasks.',
    predictionHindi: 'आत्मविश्वास और प्रभाव में वृद्धि होगी। महत्वपूर्ण कार्यों में सफलता और सम्मान मिलेगा।',
    careerPrediction: '💼 Public speaking, executive meetings, and leadership roles go exceptionally well today.',
    financePrediction: '💰 Financial reputation improves. Wise reinvestment in growth assets brings strong future gains.',
    lovePrediction: '❤️ Generous and joyful energy in romance. Celebrating milestones together enhances bond.',
    healthPrediction: '🩺 High vitality and enthusiasm. Maintain good posture and absorb morning sunlight.',
    luckyNumber: 1,
    luckyColorName: 'Royal Saffron (केसरिया नारंगी)',
    luckyColorHex: '#E65100',
    luckyDirection: 'East (पूर्व)',
    auspiciousTimeWindow: '06:30 AM - 08:15 AM',
    dailyRemedy: '🌅 Offer water (Surya Arghya) with red kumkum to the rising Sun for health and fame.',
    compatibility: 'Aries, Sagittarius'
  },
  {
    id: 'virgo',
    name: 'Virgo (Kanya)',
    hindiName: 'कन्या (Virgo)',
    symbol: '♍',
    element: 'Earth (पृथ्वी)',
    rulingPlanet: 'Mercury (Budha)',
    dailyPrediction: 'Meticulous attention to detail and practical organization solve complex problems effortlessly.',
    predictionHindi: 'बारीकियों पर ध्यान देने और व्यावहारिक संगठन से कठिन समस्याएं आसानी से हल होंगी।',
    careerPrediction: '💼 Ideal day for auditing, coding, database management, and refining operational workflows.',
    financePrediction: '💰 Excellent financial management. Budgeting and cost reduction steps succeed remarkably.',
    lovePrediction: '❤️ Practical acts of service and helpful gestures communicate care more than grand words.',
    healthPrediction: '🩺 Digestive health is good; stick to fresh, home-cooked organic meals and herbal tea.',
    luckyNumber: 5,
    luckyColorName: 'Jade Green (जैड हरा)',
    luckyColorHex: '#2E7D32',
    luckyDirection: 'North (उत्तर)',
    auspiciousTimeWindow: '11:15 AM - 01:00 PM',
    dailyRemedy: '📖 Recite Vishnu Sahasranama or chant "Om Namo Bhagavate Vasudevaya" for mental clarity.',
    compatibility: 'Taurus, Capricorn'
  },
  {
    id: 'tula',
    name: 'Libra (Tula)',
    hindiName: 'तुला (Libra)',
    symbol: '♎',
    element: 'Air (वायु)',
    rulingPlanet: 'Venus (Shukra)',
    dailyPrediction: 'Harmonious social connections and diplomatic tact bring win-win solutions in all endeavors.',
    predictionHindi: 'सामाजिक संबंधों और कूटनीतिक दृष्टिकोण से जीवन में संतुलन और सफलता मिलेगी।',
    careerPrediction: '💼 Client meetings, partnerships, and artistic collaborations flourish. Conflict resolution succeeds.',
    financePrediction: '💰 Good financial balance. Balanced investments between growth and security recommended.',
    lovePrediction: '❤️ Romantic harmony and sweet mutual appreciation. A perfect evening for a dinner date.',
    healthPrediction: '🩺 Balanced energy; light yoga, stretching, or dance keeps flexibility and mood elevated.',
    luckyNumber: 7,
    luckyColorName: 'Sky Blue (आकाशीय नीला)',
    luckyColorHex: '#0288D1',
    luckyDirection: 'West (पश्चिम)',
    auspiciousTimeWindow: '03:30 PM - 05:15 PM',
    dailyRemedy: '🌸 Donate white sweets or fragrance in a temple for Venusian harmony and prosperity.',
    compatibility: 'Gemini, Aquarius'
  },
  {
    id: 'vrischika',
    name: 'Scorpio (Vrischika)',
    hindiName: 'वृश्चिक (Scorpio)',
    symbol: '♏',
    element: 'Water (जल)',
    rulingPlanet: 'Mars & Ketu',
    dailyPrediction: 'Deep research, transformative insight, and unwavering determination unlock hidden opportunities.',
    predictionHindi: 'गहन शोध, परिवर्तनकारी अंतर्दृष्टि और अटूट संकल्प से छुपे अवसर प्राप्त होंगे।',
    careerPrediction: '💼 Strategic investigation, technical problem-solving, and confidential tasks succeed brilliantly.',
    financePrediction: '💰 Potential gains from insurance, legacy assets, or unearned wealth. Avoid risky lending.',
    lovePrediction: '❤️ Intense and loyal romantic connection. Honesty and emotional vulnerability deepen trust.',
    healthPrediction: '🩺 Detoxification practices and plenty of clean water intake support physical stamina.',
    luckyNumber: 9,
    luckyColorName: 'Maroon Red (गहरा मैरून)',
    luckyColorHex: '#800000',
    luckyDirection: 'South (दक्षिण)',
    auspiciousTimeWindow: '01:30 PM - 03:00 PM',
    dailyRemedy: '🪔 Light a mustard oil lamp for Lord Hanuman to overcome subtle obstacles.',
    compatibility: 'Cancer, Pisces'
  },
  {
    id: 'dhanu',
    name: 'Sagittarius (Dhanu)',
    hindiName: 'धनु (Sagittarius)',
    symbol: '🏹',
    element: 'Fire (अग्नि)',
    rulingPlanet: 'Jupiter (Guru)',
    dailyPrediction: 'Optimism, higher learning, and philosophical wisdom guide successful long-term expansion.',
    predictionHindi: 'सकारात्मकता, उच्च शिक्षा और ज्ञान से दीर्घकालिक योजनाओं में बड़ी सफलता मिलेगी।',
    careerPrediction: '💼 Ideal for teaching, publishing, international business, and strategic expansion planning.',
    financePrediction: '💰 Prosperity through wisdom and ethical investments. Charitable acts attract cosmic abundance.',
    lovePrediction: '❤️ Inspiring conversations with partner about future goals and spiritual travel.',
    healthPrediction: '🩺 Excellent mental vitality. Outdoor activities, hiking, or sports refresh body and spirit.',
    luckyNumber: 3,
    luckyColorName: 'Bright Yellow (पीला)',
    luckyColorHex: '#FBC02D',
    luckyDirection: 'North-East (ईशान कोण)',
    auspiciousTimeWindow: '09:00 AM - 10:45 AM',
    dailyRemedy: '💛 Apply turmeric/sandalwood tilak on forehead and honor elders or spiritual teachers.',
    compatibility: 'Aries, Leo'
  },
  {
    id: 'makara',
    name: 'Capricorn (Makara)',
    hindiName: 'मकर (Capricorn)',
    symbol: '♑',
    element: 'Earth (पृथ्वी)',
    rulingPlanet: 'Saturn (Shani)',
    dailyPrediction: 'Disciplined perseverance, practical realism, and structure lead to enduring professional victory.',
    predictionHindi: 'अनुशासन, व्यावहारिक दृष्टिकोण और लगन से स्थायी व्यावसायिक सफलता मिलेगी।',
    careerPrediction: '💼 Senior management and long-term milestone execution are favored. Persistence pays off.',
    financePrediction: '💰 Solid wealth accumulation. Sound financial discipline guarantees steady capital growth.',
    lovePrediction: '❤️ Reliable and committed presence strengthens relationships. Action speaks louder than words.',
    healthPrediction: '🩺 Joint mobility and bone health; gentle stretches and magnesium-rich diet recommended.',
    luckyNumber: 8,
    luckyColorName: 'Navy Blue (गहरा नीला)',
    luckyColorHex: '#1565C0',
    luckyDirection: 'West (पश्चिम)',
    auspiciousTimeWindow: '04:15 PM - 06:00 PM',
    dailyRemedy: '🖤 Light a sesame oil lamp under a Peepal tree or donate black sesame to honor Shani Dev.',
    compatibility: 'Taurus, Virgo'
  },
  {
    id: 'kumbha',
    name: 'Aquarius (Kumbha)',
    hindiName: 'कुंभ (Aquarius)',
    symbol: '♒',
    element: 'Air (वायु)',
    rulingPlanet: 'Saturn & Rahu',
    dailyPrediction: 'Innovative thinking, community networking, and humanitarian ideals spark revolutionary success.',
    predictionHindi: 'नवाचार, नेटवर्क और मानवीय विचारों से क्रांतिकारी और तकनीकी सफलता मिलेगी।',
    careerPrediction: '💼 Technology, social causes, group projects, and futuristic planning receive high momentum.',
    financePrediction: '💰 Financial gains through group ventures, tech investments, or social networks.',
    lovePrediction: '❤️ Open-minded companionship and shared intellectual vision strengthen emotional connection.',
    healthPrediction: '🩺 Ankle and circulatory health; take short breaks during computer work to walk around.',
    luckyNumber: 11,
    luckyColorName: 'Electric Cyan (नीला/आकाशीय)',
    luckyColorHex: '#00ACC1',
    luckyDirection: 'West (पश्चिम)',
    auspiciousTimeWindow: '01:00 PM - 02:45 PM',
    dailyRemedy: '🪔 Feed street dogs or help underprivileged workers to gain Rahu & Saturn blessings.',
    compatibility: 'Gemini, Libra'
  },
  {
    id: 'meena',
    name: 'Pisces (Meena)',
    hindiName: 'मीन (Pisces)',
    symbol: '♓',
    element: 'Water (जल)',
    rulingPlanet: 'Jupiter (Guru)',
    dailyPrediction: 'Spiritual devotion, creative imagination, and compassionate wisdom bring serene inner fulfillment.',
    predictionHindi: 'आध्यात्मिक भक्ति, रचनात्मक कल्पना और करुणा से आत्मिक शांति और सिद्धि मिलेगी।',
    careerPrediction: '💼 Creative arts, healing, psychology, and spiritual endeavors yield profound recognition.',
    financePrediction: '💰 Intuitive financial choices work well. Donating a small portion to charity enhances luck.',
    lovePrediction: '❤️ Unconditional love, spiritual empathy, and soul-level connection with your life partner.',
    healthPrediction: '🩺 Peaceful nervous system; ocean sounds, gentle music, and warm baths recharge energy.',
    luckyNumber: 3,
    luckyColorName: 'Ocean Violet (समुद्री बैंगनी)',
    luckyColorHex: '#7B1FA2',
    luckyDirection: 'North-East (ईशान कोण)',
    auspiciousTimeWindow: '08:00 AM - 09:45 AM',
    dailyRemedy: '💛 Chant "Om Gram Greem Grom Sah Gurave Namah" and offer yellow gram to temple.',
    compatibility: 'Cancer, Scorpio'
  }
];

export function getRashiById(id: string): RashiDetail {
  return RASHIPHAL_DATA.find(r => r.id === id.toLowerCase()) || RASHIPHAL_DATA[0];
}
